[workspace]
members = ["program", "cli", "sdk/rust"]
resolver = "2"

[workspace.package]
repository = "https://github.com/solana-foundation/token-acl-gate"
license = "MIT"
edition = "2021"
version = "0.2.0"

[workspace.metadata.cli]
solana = "3.1.10"

[workspace.dependencies]
token-acl-gate-client = { path = "sdk/rust", version = "0.2.0" }
solana-account-info = "=3.1.1"
solana-account = "=3.2.0"
solana-cpi = "=3.1.0"
solana-decode-error = "=2.3.0"
solana-instruction = { version = "=3.1.0", features = ["std"] }
solana-program-error = "=3.0.1"
solana-pubkey = { version = "=3.0.0", features = ["borsh"] }
solana-program-option = "=3.1.0"
solana-message = "=3.0.1"
solana-signature = "=3.1.0"
solana-signer = "=3.0.0"
spl-token-2022-interface = "=2.1.0"
solana-commitment-config = "=3.1.1"
solana-keypair = "=3.1.0"
solana-system-interface = "=3.0.0"
solana-msg = "=3.1.0"
solana-client = "=3.1.11"
solana-program-pack = "=3.1.0"
solana-transaction = { version = "=3.0.2", features = ["serde"] }
solana-clap-v3-utils = { version = "=3.1.11", features = ["agave-unstable-api"] }
solana-cli-config = "=3.1.11"
solana-logger = "=3.0.0"
solana-remote-wallet = "=3.1.11"
spl-discriminator = "=0.5.2"
spl-tlv-account-resolution = "=0.11.1"
spl-type-length-value = "=0.9.1"
spl-pod = "=0.7.2"
spl-associated-token-account-interface = "=2.0.0"
codama = "0.8.0"
serde_json = "1"
token-acl-interface = { version = "0.2.2" }
token-acl-client = { version = "0.2.2" }
token-acl = { version = "0.2.2", features = ["no-entrypoint",] }
