[workspace]
members = ["program", "cli", "sdk/rust"]
resolver = "2"

[workspace.package]
repository = "https://github.com/solana-foundation/token-acl-gate"
license = "MIT"
edition = "2021"
version = "0.2.0"

[workspace.dependencies]
token-acl-gate-client = { path = "sdk/rust", version = "0.2.0" }
solana-account-info = "^3"
solana-cpi = "^3"
solana-decode-error = "^2"
solana-instruction = { version = "^3", features = ["std"] }
solana-program-error = "^3"
solana-pubkey = { version = "^3", features = ["borsh"] }
solana-program-option = "^3"
solana-message = "^3"
solana-signature = "^3"
solana-signer = "^3"
spl-token-2022-interface = "^2"
solana-commitment-config = "^3"
solana-keypair = "^3"
solana-system-interface = "^3"
solana-msg = "^3"
solana-client = "^3"
solana-program-pack = "^3"
spl-discriminator = "0.5.0"
spl-tlv-account-resolution = "0.11.1"
spl-type-length-value = "0.8.0"
spl-pod = "0.5.1"
spl-associated-token-account-interface = "^2.0"
codama = "0.8.0"
serde_json = "1"
token-acl-interface = { version = "0.2.2" }
token-acl-client = { version = "0.2.2" }
token-acl = { version = "0.2.2", features = ["no-entrypoint",] }
