[package]
name = "token-acl-gate-cli"
version = { workspace = true }
description = "A CLI app to interact with the Token ACL Gate smart contract on solana!"
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3", features = ["cargo"] }
solana-clap-v3-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-client = { workspace = true }
solana-logger = { workspace = true }
solana-remote-wallet = { workspace = true }
tokio = { version = "1", features = ["full"] }
token-acl-gate-client = { workspace = true }
spl-token-2022-interface = { workspace = true }
token-acl-client = { workspace = true }
token-acl-interface = { workspace = true }
solana-pubkey = { workspace = true, features = ["serde"] }
solana-keypair = { workspace = true }
solana-signature = { workspace = true }
solana-transaction = { workspace = true }
solana-instruction = { workspace = true }
solana-commitment-config = { workspace = true }

[[bin]]
name = "token-acl-gate-cli"
path = "src/main.rs"
