[package]
name = "token-acl-gate-client"
version = { workspace = true }
description = "A rust library for the Token ACL Gate program with generated client code."
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
name = "token_acl_gate_client"

[dependencies]
solana-account-info = { workspace = true }
solana-program-error = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { version = "^3", features = ["curve25519", "borsh"] }
solana-cpi = { workspace = true }
solana-client = { workspace = true, optional = true }
num-derive = "0.4.2"
num-traits = "0.2.19"
borsh = { version = "^1.0" }

[dev-dependencies]
litesvm = "^0.9"
spl-associated-token-account-interface = "^2.0"
spl-token-2022-interface = { workspace = true }
solana-system-interface = { workspace = true }
tokio = { version = "^1.20", features = ["rt-multi-thread", "macros"] }
solana-program-option = { workspace = true }
solana-program-pack = { workspace = true }
solana-keypair = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { version = "^3", features = ["serde"] }
token-acl-interface = { workspace = true }
token-acl = { workspace = true }
token-acl-client = { workspace = true }

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(feature, values("anchor", "anchor-idl-build", "serde", "fetch"))',
]
